kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-local-storage

bases:
  - ../../../../../../Applications/local-storage/create-local-volumes/base

patches:
  - target:
      kind: LocalVolume
      name: local-storage
    patch: |-
      - op: replace
        path: /metadata/name
        value: monitoring-local-storage
      - op: replace
        path: /spec/managementState
        value: Managed
      - op: replace
        path: /spec/logLevel
        value: Debug
      - op: replace
        path: /spec/storageClassDevices
        value:
          - devicePaths:
            - /dev/sdc
            fsType: xfs
            storageClassName: monitoring
            volumeMode: Filesystem
